;RICARDO DOMINGUEZ OJEDA, 202325963, DO202325963@ALM.BUAP.MX
;OBJETIVO: MOSTRAR LA APLICACION DE ALGUNOS MNEMONICOS                
                
INICIO:                 ;DEFINIMOS LA ETIQUETA DE INICIO

    ;IMPRIMIR EN PANTALLA LA CADENA DE BIENVENIDA
    MOV AH, 09H         ; SERVICIO DE LA INT 21H QUE IMPRIME EN PANTALLA
    MOV DX, OFFSET CAD  ; OFFSET CALCULA LA DIRECCION DE CAD
    INT 21H
           
    ;DETENER EL FIN PARA OBSERVAR EN PANTALLA
    MOV AH, 01H         ;SERVICIO PARA LEER UN CARACTER ES EL 01H, INT 21H
    INT 21H       
 
    MOV AL,05H          ; AL = 5  
    MOV BL,02H          ; BL = 2
    
    ;SUMAR
    ADD AL,BL           ; AL = AL + BL
    MOV RES_SUM,AL      ; GUARDAR EN UNA NUEVA VARIABLE LA SUMA
    
    ;RESTA
    MOV AL,05H          ; AL = 5 
    SUB AL,BL           ; AL = AL - BL
    MOV RES_RES,AL      ; GUARDAR EN UNA NUEVA VARIABLE LA RESTA
    
    ;MULTIPLICAR 
    MOV AL, 05H         ; AL = 5
    MUL BL              ; AX = AL * BL
    MOV RES_MUL, AX     ; GUARDAR EN UNA NUEVA VARIABLE EL PRODUCTO   
    
    ;DIVISION
    MOV AL, 05H         ; AL = 5
    DIV BL              ; AL = AL / BL, RESIDUO EN AH
    MOV COS_DIV, AL     ; GUARDAR EN UNA NUEVA VARIABLE EL COCIENTE 
    MOV RES_DIV, AH     ; GUARDAR EN UNA NUEVA VARIABLE EL RESIDUO         
                        
    ;FIN DEL PROGRAMA
    INT 20H         
                                            
           
;DEFINICION DE VARIABLES - DIRECTIVA DB 
    RES_SUM DB 00H      ; VARIABLE PARA LA SUMA
    RES_RES DB 00H      ; VARIABLE PARA LA RESTA
    RES_MUL DW 00H      ; VARIABLE PARA EL PRODUCTO
    COS_DIV DB 00H      ; VARIABLE PARA EL COCIENTE DE LA DIVISION
    RES_DIV DB 00H      ; VARIABLE PARA EL RESIDUO DE LA DISISION
    CAD     DB "BIENVENIDOS A MI CALCULADORA$"      ; CADENA DE BIENVENIDA                  