;RICARDO DOMINGUEZ OJEDA, 202325963, DO202325963@ALM.BUAP.MX
;OBJETIVO: PROGRAMA HOLA MUNDO

INICIO: ; DEFINIMOS LA ETIQUETA INICIO
        ; SALIDA ESTANDAR
        ; IMPRIMIR EN PANTALLA UNA CADENA "HOLA MUNDO"
 
        MOV AH, 09H                 ; SERVICION QUE IMPRIME CADENA EN PANTALLA DE LA INT 21H
        MOV DX, OFFSET CAD          ; OFFSET CALCULA LA DIRECCION DE CAD
        INT 21H                     ; TODAS LAS INTERRUPCIONES TIENEN SERVICIOS          
        
        ; IMRPIMIR CAD2
        MOV AH, 09H
        MOV DX, OFFSET CAD2
        INT 21H
        
        ; VAMOS A DETENER EL FIN LEYENDO UN CARACTER
        ; SERVICIO PARA LEER UN CARACTER ES EL 01H, INT 21H
        
        MOV AH, 01H                 ; PULSAR PARA LA EJECUCION, PARA RECIVIR UNA ENTRADA
        INT 21H                     ; LA LECTURA LA DEJA EN EL AL = CODIGO ASCII
        
        INT 20H                     ; FIN DEL PROGRAMA

;DEFINICION DE VARIABLES - DIRECTIVA DB    
    
CAD       DB "HOLA MUNDO", 0DH, 0AH, "$"    ;TODA CADENA DEBE TERMINAR CON EL SIMBOLO $
CAD2      DB "ESTE ES MI PROGRAMA$"